version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-southeast-1:353679870343:task-definition/cicd-task-definition:4"
        LoadBalancerInfo:
          ContainerName: "cicd-container"
          ContainerPort: 8081 # used by CodeDeploy and ECS to map incoming traffic to the correct port on the container