name: Sync to AWS CodeCommit

on:
  push:
    branches:
      - main  # Trigger on pushes to main branch

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Push to GitHub main branch
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_CENTRICORE_SHA }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_CENTRICORE_SHA }}
          aws-region: ap-southeast-1

      - name: Push to AWS CodeCommit
        run: |
          git remote add codecommit https://git-codecommit.ap-southeast-1.amazonaws.com/v1/repos/test-repo-for-cicd-pipeline
          git fetch codecommit
          git checkout main
          git pull origin main
          git push codecommit main
