name: Sync to AWS CodeCommit

on:
  push:
    branches:
      - master  # Trigger on pushes to master branch

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install ESLint
        run: npm install eslint eslint-plugin-react

      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_CENTRICORE_SHA }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_CENTRICORE_SHA }}
          aws-region: ap-southeast-1

      - name: Set up Git config        
        run: |
          git config --global credential.helper '!aws codecommit credential-helper $@'
          git config --global credential.UseHttpPath true

      - name: Push to AWS CodeCommit
        run: |
          git remote add codecommit https://${{ secrets.AWS_USERNAME_CENTRICORE_SHA_HTTPS_GIT_CREDS_FOR_CODECOMMIT }}:${{ secrets.AWS_PASSWORD_CENTRICORE_SHA_HTTPS_GIT_CREDS_FOR_CODECOMMIT }}@git-codecommit.ap-southeast-1.amazonaws.com/v1/repos/test-repo-for-cicd-pipeline
          git fetch codecommit
          git push codecommit master
