name: Sync to AWS CodeCommit

on:
  push:
    branches:
      - master  # Trigger on pushes to master branch

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # - name: Push to GitHub master branch
      #   run: |
      #     git push origin master

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_CENTRICORE_SHA }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_CENTRICORE_SHA }}
          aws-region: ap-southeast-1

      - name: Set up Git config
        # run: |
        #   git config --global user.email "actions@github.com"
        #   git config --global user.name "GitHub Actions"
        #           git config credential.https://git-codecommit.ap-southeast-1.amazonaws.com/v1/repos/test-repo-for-cicd-pipeline.username ${{ AWS_USERNAME_CENTRICORE_SHA_HTTPS_GIT_CREDS_FOR_CODECOMMIT }}
        run: |
          git config --global credential.helper '!aws codecommit credential-helper $@'
          git config --global credential.UseHttpPath true
          git config credential.helper 'store'

      - name: Push to AWS CodeCommit
        run: |
          git remote add codecommit https://${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}@git-codecommit.ap-southeast-1.amazonaws.com/v1/repos/test-repo-for-cicd-pipeline
          git fetch codecommit
          git checkout master
          git pull origin master
          git push codecommit master
